name: Run Test Cases
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: yarn
            - name: Check code Linting
              run: yarn lint
            - name: Run tests
              run: yarn test
